Fixed checkbox label text overflow
phoenixlan/phoenixapi-v1 pull request #50
Opened 2024-04-08 19:21 UTC by simsine

remind me to never do frontend again

![image](https://github.com/phoenixlan/phoenixapi-v1/assets/89988615/ad29c5c1-47eb-47aa-9bf2-a5fa41106880)

2024-04-08 20:25 UTC, HenrikEngen commented
![Screenshot_20240408_222248_Chrome](https://github.com/phoenixlan/phoenixapi-v1/assets/30247084/ced9fc5d-98b7-4d53-8d1d-ae6705d2112b)

The issue is fixed, good job! But I notice another visual bug, pirk pirk..
The space between the check boxes are not the same

2024-04-08 20:32 UTC, HenrikEngen requested changes
![image](https://github.com/phoenixlan/phoenixapi-v1/assets/30247084/e84db26b-c6d8-49a5-9d0a-e45dd55798db)

The issue is fixed, good job! But I notice another visual bug, pirk pirk..
The space between the check boxes are not the same

2024-04-08 21:16 UTC, simsine commented
> ![image](https://private-user-images.githubusercontent.com/30247084/320640094-e84db26b-c6d8-49a5-9d0a-e45dd55798db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MTExOTksIm5iZiI6MTcxMjYxMDg5OSwicGF0aCI6Ii8zMDI0NzA4NC8zMjA2NDAwOTQtZTg0ZGIyNmItYzZkOC00OWE1LTlkMGEtZTQ1ZGQ1NTc5OGRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDIxMTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ODY3ZmIzNjllNWZkMDcyMDA3NDUwMGUxNzQzZTAzYzBjNDU0ZjAxMGFjMDVhYmFiMzRjMmRmOWQ4MDdhM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GsPQc7tNlNswiMmLUh6J6WFK6udTRoQsxstaV5vFOTg)
> 
> The issue is fixed, good job! But I notice another visual bug, pirk pirk.. The space between the check boxes are not the same

![image](https://github.com/phoenixlan/phoenixapi-v1/assets/89988615/54a011c0-6db8-41e1-8dce-df3e4935d68d)
sigh

2024-04-09 10:35 UTC, petterroea requested changes

2024-04-09 11:45 UTC, simsine commented on staticContent/public/static/global.css
> +.label-text {
Not really, the label-text and mark classes are div wrappers for the component slot and checkbox respectively, which per [the source code](https://github.com/vikignt/svelte-mui/blob/4b95448fdf5a77629fe1e9d314499d97e4d77aab/src/Checkbox.svelte#L77) has no interface to be changed.
Is there something i am not seeing here?

2024-04-09 18:08 UTC, HenrikEngen approved these changes

2024-04-09 18:28 UTC, simsine commented on staticContent/public/static/global.css
> +.label-text {
I also tried increasing the css specificity in order to overwrite the component css class attributes but this does not work either.
!important is the only thing that works it seems

2024-04-16 13:49 UTC, petterroea commented
I am also happy, seems like @simsine put in due dilligence. let's get this merged!

2024-04-16 13:49 UTC, merged